echobind/react-native-template

.vscode/settings.json, devDependencies.json, tsconfig.json
This PR adds [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin) as a dependency to a project in order to get intellisense for styled components.
- Adds typescript-styled-plugin as a dev dependency
- Configures typescript-styled-plugin as a compiler option plugin
- Adds vscode settings with echobind specific styling
Fixes #5
=> Adds typescript-styled-plugin to compiler options as plugin

.babelrc, babel.config.js, dependencies.json, devDependencies.json, setup/detox.json, src/screens/IntroScreen/component.tsx, src/styles/fonts.ts, storybook/addons.js, storybook/storybook.js
- Updated dependencies
- Removed unsupported addons
- Added backgrounds addon
- removed references to missing fonts
NOTE: verified app run on Android... will test actual Storybook running on Android in another effort to add npm scripts to the package.json. (i.e. our adb reverse `preandroid` script)
...in description
- [ 👍] Checked on iOS
- [ 👍] Checked on Android
Fixes #10
=> Upgrade to Storybook 4 and React-Native 0.57

_templates/component/new/component.ejs
- Defines default props to be used with an SFC component
- Destructures children from view props
(prefer animated gif)
Fixes #8
=> Fix default props for component SFC template

setup/index.js
Overview / Description
Delete `.babelrc` file upon repository setup, to allow `babel.config.js` to be resolved by metro bundler
- Delete file when running `node ./setup` script.
(prefer animated gif)
=> Remove .babelrc file

setup/jest.json
Overview / Description
Jest setup was incorrect for newer react-native version requiring newer language feature proposals.
Using included transform for jest inside react-native resolved JS transform issue.
- Switch `.js` transform config to use `react-native`'s `jest` pre-processor.
- Disable Typescript `isolatedModules` for tests since tests usually have an export.
Fixes #21
=> Fix Jest Setup w/ TS

.gitattributes, .gitignore
Looks like a `.gitattributes` file was checked in. That was causing git to get really confused.
This also ignores `.jest` as I doubt we'll need anything there
- Remove .gitattributes
- add .jest to .gitignore
n/a
Fixes #2
=> chore(workflow): remove stray `.gitattributes`, add .jest to gitnore

_templates/component/new/component.ejs, _templates/screen/new/component.ejs
This changes the JSDoc comments in component templates to have the correct format.
- jsdoc should be `/** thing */` not `/** thing **/`
n/a
Fixes #7
=> fix(workflow): correctly use JSDoc comments in templates

setup/index.js
This commits the code to git immediately after running `setup`. Users are expected to add the rmote, but this ensures that additional setup tasks don't become part of the initial app generation commit.
- run `git add .. && git commit -m "Initialize new React Native project."` as the current user.
n/a
Fixes #4
=> chore(workflow): automatically run git commit after setup

_templates/component/new/stories.ejs
Previously, our component story template had classNames in it. I double-checked the rest of the project and this looks like the only occurrence.
- remove it
n/a
~- [ ] Added docs~
Fixes #9
=> fix(generators): don't use className in component story generator

husky.config.js, setup/index.js, setup/scripts.json
precommit hooks via husky are broken now, so we need to upgrade. this moves config to husky.config.js.
it also cleans up git init and removes the entire setup directory in one command (this will keep getting larger)
Overview / Description
- migrate husky config to `husky.config.js`
- remove stray git references on setup
- remove entire setup directory when we're done with it vs individual files
- call `git init` 🤦‍♂️ 
n/a
~- [ ] Added docs~
Fixes #35
=> fix(install): upgrade husky, move to new config, fix git init

src/App.tsx
When a new project when generated the Android project would run but throw an odd error without a lot of detail (See #48).
- Re-order imports so storybook is imported after reactotron config 
Fixes #48
=> fix(android): re-order imports to fix issue on android

.github/PULL_REQUEST_TEMPLATE.md
We have a GH Check that does this for us now.
=> chore(workflow): remove "conventional changelog" checkbox

setup/index.js
Sets initial version of generated projects to `0.0.1`
- Update *setup* script to run `react-native-version` to modify the version code for iOS + Android so *fastlane* auto increment feature will work without manual changes in native code to set initial version.
- Remove step to delete `.babelrc`, newer versions of RN projects generate a `babel.config.js` instead.
Fixes #15
=>  feat(auto-version): automate initial version for iOS + Android projects to allow fastlane versioning

README.md
As a new developer, experimenting with echobinds template, I should be instructed to add the react-native-cli package so that I know what dependencies to install prior to running the template.
- Adds react-native-cli package install as the first step
=> chore(docs): add react-native-cli install step

README.md
Fix broken links in docs section (issue #89 )
=> fix: links in the docs section

README.md, package.json
This PR makes the following changes:
- update README with section on publishing
- fix broken link in TOC for CI/deployment
- add `postpublish` script
Fixes #95
=> docs(readme): document how to release

template/_templates/component/new/component.ejs, template/_templates/component/new/stories.ejs, template/package.json, template/src/components/Button/Button.stories.tsx, template/src/components/Button/Button.tsx, template/src/components/Button/index.ts, template/src/components/Login/Login.stories.tsx, template/src/components/Login/Login.tsx, template/src/components/Login/index.ts, template/src/components/TextInput/TextInput.stories.tsx, template/src/components/TextInput/TextInput.tsx, template/src/components/TextInput/index.ts, template/src/screens/IntroScreen/IntroScreen.tsx, template/src/screens/LoginScreen/LoginScreen.tsx, template/src/styles/colors.ts, template/storybook/stories/index.ts
*  Base Login component added, updated Login Screen to reference 
*  Added TextInput and Button Primatives as styled components
(still needs work to implement the icon with the textInput)
*  Updated component.ejs to use container instead of the old view
Expect to be able to Navigate to Login Screen From Intro and then see new Login Component with some placeholder navigation events
=> feature: Add Login Component scaffold

template/.solidarity
This updates the RN cli check to look for a local version using "which react-native". If `which react-native` does not return `node_modules/.bin/react-native` we assume global.
See screenshots for examples of pass/fail.
Fixes #94
=> feat(solidarity): Ensure local version of RN cli

template/.solidarity
`--fix` works if the user doesn't have it installed, but not for upgrading. This updates the error message to reflect both.
Screenshot:
=> chore(solidarity): Update applesimutils error message

template/package.json
`eslint-plugin-import` is specified in the eslint config, however not in the dependencies.
This PR adds it as a dev dependency. (Necessary for VS Code eslint to work)
=> fix(dependencies): adds missing eslint-plugin-import dependency

template/README.md, template/src/components/Button/Button.tsx, template/src/components/Login/Login.tsx, template/src/components/TextInput/TextInput.tsx, template/src/types/AccessibilityRole.ts
This PR adds accessibility features and a base readme for the template after initialization. Included is the AccessbilityRole type interface to be used with our styled-components so that you may still get IntelliSense and know the acceptable values.
Base readme file will also now be included with project init with information about running tests & developing for accessibility.
=> feat(accessibility): Label/Role & Readme file

template/ios/HelloWorld/Info.plist, template/package.json
Adds the start script back to the package json with reset cache parameter
Update Storybook to resolve async storage warning
Update info.plist to resolve the app display name to match project name
issue #116  start script
issue #121 async storage warning
issue #131 iOS display name
=> chore: Start Script & Fix Display Name

template/.solidarity, template/Gemfile.lock, template/src/utils/trimText/index.ts, template/src/utils/trimText/trimText.test.ts, template/src/utils/trimText/trimText.ts
This adds a version check for bundler when running solidarity. Ensures it is min version of 2.0.2
This also adds a simple textTrim utility that has a test so that if you run `yarn test` it has a test it can run. This will be used for presentation purposes at Epic Conf
=> feat: Update solidarity bundler check

template/src/App.tsx
Hey all! 
This is as much a proposal at it is a feature. I feel like the template has gotten a little long in the tooth, (i.e. outdated), and I'm trying to clean it up and make it as appealing as possible for public use.
The main thing here is that I have converted the root app component to be functional instead of class-based. 🎉 
The proposal-part is that I removed all of the state-management boilerplate. 
I think it doesn't add any value and instead just makes the template look messy.
Let me know what you think!
I tested this and its functionally equivalent to the old files :)
=> feat: Converts Root App File to a Functional Component and Removes Unused Boilerplate
